Lands/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lr/', include('lrms.urls')),
    url(r'^owner/', include('owner.urls')),
]

lrms/urls.py
from django.conf.urls import url
from views import (Home, OwnerDetail, OwnerPropertyList, PropertyDetail, PaymentCreate, PaymentDetail, PropertyAdd, SignUp, Cover, Tafela,
                   PropertyList, PropertyPage, PaymentHistory, LandsUserProfile, check_nrc, add_owner)
from django.contrib.auth import views as auth_views

app_name = 'lrms'

urlpatterns = [
    # Auth URLs
    url(r'^signup/$', SignUp.as_view(), name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Misc URLs
    url(r'^$', Cover.as_view(), name='cover'),
    url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/(?P<pk>[0-9]+)/', LandsUserProfile.as_view(), name='lands_user_profile'),
    # Property URLs
    url(r'property/add/(?P<owner_pk>[0-9]+)/$', PropertyAdd.as_view(), name='property_add'),
    url(r'^property/list/$', PropertyList.as_view(), name='property_list'),
    url(r'^property/(?P<pk>[0-9]+)/$', PropertyDetail.as_view(), name='property_detail'),
    url(r'^property/page/(?P<property_pk>[0-9]+)/$', PropertyPage.as_view(), name='property_page'),
    # payment URLs
    url(r'^payment/add/(?P<property_pk>[0-9]+)/$', PaymentCreate.as_view(), name='payment_add'),  # pk is for the property
    url(r'^payment/(?P<pk>[0-9]+)/$', PaymentDetail.as_view(), name='payment_detail'),
    url(r'^payment/history/(?P<property_pk>[0-9]+)/$', PaymentHistory.as_view(), name='payment_history'),
    # Tests
    url(r'^(?P<nangoma>\d+)/$', Tafela.as_view(), name='test'),
    # owner urls
    url(r'^property/check/$', check_nrc, name='nrc_check'),
    url(r'^owner/add/(?P<non_existing_owner>[0-9]+)/$', add_owner, name='add_owner'),
    url(r'^owner/(?P<pk>[0-9]+)/$', OwnerDetail.as_view(), name='owner_detail'),
    url(r'^owner/plotlist/(?P<owner_pk>[0-9]+)/$', OwnerPropertyList.as_view(), name='property_list_specific'),
]

owner/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (Home, PropertyDetail, Landing)

app_name = 'owner'

urlpatterns =[
    # url(r'^login/$', auth_views.LoginView.as_view(), name='owner_login'),
    url(r'^$', Landing.as_view(), name='landing'),
    url(r'^(?P<owner_pk>[0-9]+)/$', Home.as_view(), name='owner_home'),
    url(r'^property/(?P<pk>[0-9]+)/$', PropertyDetail.as_view(), name='property_detail')
]

owner/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from lrms.models import OwnerProfile
from django.contrib.auth.models import User

class Owner(OwnerProfile):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING())

owner/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView, DetailView
from lrms.models import Property, OwnerProfile


class Home(TemplateView):

    template_name = 'owner/home.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            owner = OwnerProfile.objects.get(pk=self.kwargs['owner_pk'])
            plots = Property.objects.filter(owner=owner)

            context = {
                'property': plots,
                'owner': owner
                       }

            return render(request, self.template_name, context)
        else:
            return redirect('owner:owner_login')


class PropertyDetail(DetailView):
    model = Property
    template_name = 'owner/property_detail.html'


class Landing(TemplateView):
    template_name = 'owner/nrc_search.html'

    def get(self, request, *args, **kwargs):
        owner_pk = None
        query = request.GET.get('q')

        if query:
            try:
                owner = OwnerProfile.objects.get(nrc__icontains=query)
                owner_pk = owner.pk
                return redirect('owner:owner_home', owner_pk=owner_pk)

            except:
                print 'oho, fya pena nomba!!'

        context = {
                'query': query
            }
        return render(request, self.template_name, context)

templates/owner/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Base{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'owner/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'owner/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'owner/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'owner/css/landing-page.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Land Record Management System</a>
        <a class="btn btn-primary" href="#">Sign In</a>
      </div>
    </nav>

      {% block content %}
        <h3>Bare Base</h3>
      {% endblock %}

    <!-- Footer-->
    <footer class="my-auto position-static blockquote-footer text-center text-success">
        <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
        <div class="inner ">
          <p>Copyright <a href="">Elysian</a>, by <a href="">Front Dev Team</a>.</p>
        </div>
      </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'owner/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'owner/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

templates/owner/home.html
{% extends 'owner/base.html' %}
{% block title %}
    home
{% endblock %}

{% block content %}
<div class="jumbotron text-center">
<h3>{{ owner }}</h3>
    <p>
    {% if property.count == 1 %}
        You own {{ property.count }} property.
    {% elif property.count > 1%}
        You own {{ property.count }} properties
    {% else %}
        You Do Not Own Any Land Property, Apply For Land at your Local Council.
    {% endif %}
    </p>
    <div class="content-justify-center">
    {% for property in property %}
        <ol>
            <li>
                <a href="{% url 'owner:property_detail' pk=property.pk %}">
                {{ property }}--{{ property.local_authority.upper }}
                </a>
            </li>
        </ol>

    {% endfor %}
    </div>
</div>

{% endblock %}

templates/owner/nrc_search.html
{% extends 'owner/base.html' %}
{% block title %}Search NRC{% endblock %}

    {% block content %}
    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Welcome to the Land Record Management System. Enter your NRC below to see your properties</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form action="">
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="text" name="q" class="form-control form-control-lg" placeholder="Enter your NRC..."
                  value="{{ request.GET.q }}">
                </div>
                <div class="col-12 col-md-3">
                  <button class="btn btn-block btn-lg btn-primary">Search</button>
                </div>
              </div>
            </form>
              {% if query != None %}
                  <p>We Could Not Find The NRC you entered. Please Try again or check with your Local Council for assistance.</p>
              {% endif %}
          </div>
        </div>
      </div>
    </header>
    {% endblock %}

templates/owner/property_detail.html
{% extends 'owner/base.html' %}

{% block title %}
    Property Details
{% endblock %}
{% block content %}
    <div class="text-center" >
        <h3>{{ property }}</h3>
    </div>
    <ol class="badge-success">
        <li>Property Owner: {{ property.owner }}</li>
        <li>Property Successor: {{ property.successor}} - {{ property.successor_relation }}</li>
        <li>Property Area: {{ property.area }}</li>
        <li>Holding Number: {{ property.holding_number }}</li>
        <li>Property Type: {{ property.type }}</li>
        <li>Local Authority: {{ property.local_authority }}</li>
        <li>Current Balance: {{ property.balance }}</li>
    </ol>
    <a class="btn btn-sm btn-primary" href="{% url 'owner:owner_home' owner_pk=property.owner.pk%}">
        Return To Property List
    </a>
{% endblock %}