Lands/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lr/', include('lrms.urls')),
    url(r'^owner/', include('owner.urls')),
]

lrms/urls.py
from django.conf.urls import url
from views import (Home, OwnerDetail, OwnerPropertyList, PropertyDetail, PaymentCreate, PaymentDetail, PropertyAdd, SignUp, Cover, Tafela,
                   PropertyList, PropertyPage, PaymentHistory, LandsUserProfile, check_nrc, add_owner)
from django.contrib.auth import views as auth_views

app_name = 'lrms'

urlpatterns = [
    # Auth URLs
    url(r'^signup/$', SignUp.as_view(), name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Misc URLs
    url(r'^$', Cover.as_view(), name='cover'),
    url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/(?P<pk>[0-9]+)/', LandsUserProfile.as_view(), name='lands_user_profile'),
    # Property URLs
    url(r'property/add/(?P<owner_pk>[0-9]+)/$', PropertyAdd.as_view(), name='property_add'),
    url(r'^property/list/$', PropertyList.as_view(), name='property_list'),
    url(r'^property/(?P<pk>[0-9]+)/$', PropertyDetail.as_view(), name='property_detail'),
    url(r'^property/page/(?P<property_pk>[0-9]+)/$', PropertyPage.as_view(), name='property_page'),
    # payment URLs
    url(r'^payment/add/(?P<property_pk>[0-9]+)/$', PaymentCreate.as_view(), name='payment_add'),  # pk is for the property
    url(r'^payment/(?P<pk>[0-9]+)/$', PaymentDetail.as_view(), name='payment_detail'),
    url(r'^payment/history/(?P<property_pk>[0-9]+)/$', PaymentHistory.as_view(), name='payment_history'),
    # Tests
    url(r'^(?P<nangoma>\d+)/$', Tafela.as_view(), name='test'),
    # owner urls
    url(r'^property/check/$', check_nrc, name='nrc_check'),
    url(r'^owner/add/(?P<non_existing_owner>[0-9]+)/$', add_owner, name='add_owner'),
    url(r'^owner/(?P<pk>[0-9]+)/$', OwnerDetail.as_view(), name='owner_detail'),
    url(r'^owner/plotlist/(?P<owner_pk>[0-9]+)/$', OwnerPropertyList.as_view(), name='property_list_specific'),
]

lrms/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
from django.urls import reverse
from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# imports for custom user
from django.contrib.auth.models import AbstractUser


GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
)
RELATION = (
    ('gma', 'Grand Mother'),
    ('gda', 'Grand Father'),
    ('dad', 'Father'),
    ('mom', 'Mother'),
    ('sis', 'Sister'),
    ('bro', 'Brother'),
    ('unc', 'Uncle'),
    ('aun', 'Auntie'),
    ('cuz', 'Cousin'),
    ('son', 'Son'),
    ('dot', 'Daughter'),
)
PROPERTY_TYPE = (
    ('R', 'Residential'),
    ('C', 'Commercial'),
)
PAYMENT_TYPES = (
    ('RNT', 'Payment for Land Rentals'),
    ('NO', 'New Occupancy'),
    ('OLR', 'Old Land Record'),
    ('PF', 'Penalty Fees'),
)


class OwnerProfile(models.Model):
    first_name = models.CharField(max_length=20, blank=False, null=False, default='John')
    middle_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=False, null=False, default='Nangoma')
    gender = models.CharField(max_length=1, choices=GENDER, default='')
    nrc = models.CharField(max_length=20, blank=False, null=False, unique=True)
    telephone = models.CharField(max_length=15, default='', null=True, blank=True)
    address = models.CharField(max_length=50, blank=False, null=True)
    email = models.EmailField(blank=True, null=True)
    date_of_birth = models.DateField(verbose_name='Date of Birth', default=datetime.date(1995, 04, 13))

    @property
    def age(self):
        age = int((datetime.datetime.now().date() - self.date_of_birth).days / 365.25)
        return age

    def get_absolute_url(self):
        return reverse('owner-detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        owner_id = (str(self.first_name) + ' ' + str(self.middle_name) + ' ' + str(self.last_name))
        return owner_id


class Authority(models.Model):
    name = models.CharField(max_length=50)
    district = models.CharField(max_length=30)

    def __unicode__(self):
        return str(self.name)


class LandsUser(AbstractUser):
    man_number = models.CharField(max_length=20, default='-----', null=False, blank=False)
    phone = models.CharField(max_length=13, null=True, blank=True)
    local_authority = models.ForeignKey(Authority, on_delete=models.DO_NOTHING, null=True)
    position = models.CharField(max_length=20, null=False, blank=False, help_text="JOB TITLE")

    def __unicode__(self):
        return str(self.get_full_name()) + '-' + str(self.man_number) + '-' + str(self.local_authority)


class Property(models.Model):
    owner = models.ForeignKey(OwnerProfile, on_delete=models.DO_NOTHING, default=1, related_name='owner')
    # address = models.CharField(max_length=50, blank=False, null=False)  # probably redundant
    local_authority = models.CharField(max_length=50, blank=False, null=False)
    area = models.CharField(max_length=50, blank=False, null=False)
    holding_number = models.CharField(max_length=50, blank=False, null=False, unique=True)
    type = models.CharField(max_length=1, choices=PROPERTY_TYPE, blank=False, null=True, default='R')
    balance = models.FloatField(verbose_name='Balance Due')
    successor = models.CharField(max_length=50, blank=False, null=True)
    successor_relation = models.CharField(max_length=3, blank=False, null=True, choices=RELATION,
                                          verbose_name='Relationship With Next Of Kin', default='son')
    added_by = models.ForeignKey(LandsUser, on_delete=models.DO_NOTHING, null=True)
    added_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        property_id = (str(self.holding_number).upper() + ' - ' + str(self.area).upper())
        return property_id

    def get_absolute_url(self):
        return reverse('lrms:property_detail', kwargs={'pk': self.pk})


# land rate payments on property
class Payment(models.Model):
    received_from = models.ForeignKey(OwnerProfile, on_delete=models.DO_NOTHING,
                                      related_name='payer', default=1)  # auto fill
    received_by = models.ForeignKey(LandsUser, on_delete=models.DO_NOTHING)  # auto fill
    property = models.ForeignKey(Property, on_delete=models.DO_NOTHING)  # auto fill
    amount = models.FloatField()
    description = models.CharField(max_length=5, choices=PAYMENT_TYPES, blank=False, null=False, default='RNT')
    date = models.DateTimeField(auto_now_add=True)
    payment_number = models.CharField(max_length=50, default='elysian')  # auto generate payment number

    def generate_payment_number(self):
        plot_number = self.property.holding_number
        # number of payments made on this property
        payments_number = Payment.objects.filter(property=self.property).count()
        payment_number = str(plot_number) + str(self.description) + str(payments_number)
        return payment_number

    def __unicode__(self):
        payment = (str(self.received_from) + ' ' + str(self.property) + '-' + str(self.date))
        return payment

    def get_absolute_url(self):
        return reverse('lrms:payment_detail', kwargs={'pk': self.pk})

lrms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import LandsUser, Property, OwnerProfile


class LandsUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = LandsUser
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'local_authority', 'man_number',)


class LandsUserChangeForm(UserChangeForm):

    class Meta:
        model = LandsUser
        fields = ('phone', 'email', 'local_authority',)


class OwnerForm(forms.ModelForm):
    class Meta:
        model = OwnerProfile
        fields = '__all__'


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = '__all__'

lrms/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views import View
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from . forms import OwnerForm, PropertyForm, LandsUserCreationForm
from . models import OwnerProfile, Property, Payment, LandsUser
from django.contrib.auth.models import User


class Home(TemplateView):
    template_name = 'lrms/home.html'

    # Search Views to find house number before making the payment.
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            query_list = None
            query = request.GET.get('q')

            if query:
                query_list = Property.objects.all()
                query_list = query_list.filter(holding_number__icontains=query)

        else:
            return redirect('lrms:cover')

        context = {
            'query_list': query_list,
        }

        return render(request, self.template_name, context)


class Cover(TemplateView):
    template_name = 'lrms/cover.html'


# Owner classes
# -------------------------------------------------------------------------------------
class OwnerDetail(DetailView):
    model = OwnerProfile
    template_name = 'lrms/owner_detail.html'


def add_owner(request, non_existing_owner):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = OwnerForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save(commit=False)
            form.save()
            new_owner_pk = form.instance.pk
            # redirect to add property
            return redirect('lrms:property_add', owner_pk=new_owner_pk)
    # if GET request
    else:
        form = OwnerForm()
    context = {'non_existing_owner': non_existing_owner,
               'form': form}
    return render(request, 'lrms/owner_create.html', context)


def check_nrc(request):  # checking to see if an owner exists before adding a property to the database
    try:
        nrc = request.GET.get('nrc')
        owner = OwnerProfile.objects.get(nrc__exact=nrc)
        if owner:
            return redirect('lrms:property_add', owner_pk=owner.pk)

    except OwnerProfile.DoesNotExist:
        non_existing_owner = 1
        return redirect('lrms:add_owner', non_existing_owner=non_existing_owner)


# Property classes
# -------------------------------------------------------------------------------------
class PropertyAdd(CreateView):
    model = Property
    fields = ['holding_number', 'type', 'area', 'successor', 'successor_relation', ]

    def form_valid(self, form):
        # Getting the owner model
        try:
            owner = OwnerProfile.objects.get(pk=self.kwargs['owner_pk'])
        except OwnerProfile.DoesNotExist:
            return HttpResponse('Something went wrong, we couldn\'t find the owner you specified. Please try again')
        form.instance.owner = owner
        print owner
        form.instance.local_authority = self.request.user.local_authority
        print form.instance.local_authority
        form.instance.balance = 0.00
        print form.instance.balance
        form.instance.added_by = self.request.user
        print form.instance.added_by
        return super(PropertyAdd, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PropertyAdd, self).get_context_data(**kwargs)
        context['owner'] = OwnerProfile.objects.get(pk=self.kwargs['owner_pk'])
        return context

class PropertyUpdate(UpdateView):
    model = Property
    fields = ['owner']


class PropertyDetail(DetailView):
    model = Property
    template_name = 'lrms/property_detail.html'


class PropertyList(ListView):
    model = Property
    context_object_name = 'Properties'
    template_name = 'lrms/property_list.html'


class PropertyPage(TemplateView):
    template_name = 'lrms/property_page.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            plot = Property.objects.get(pk=self.kwargs['property_pk'])

            context = {'property': plot, }

            return render(request, self.template_name, context)
        else:
            return redirect('lrms:cover')


class OwnerPropertyList(TemplateView):
    template_name = 'lrms/owner_property_list.html'

    def get(self, request, *args, **kwargs):
        owner = OwnerProfile.objects.get(pk=self.kwargs['owner_pk'])
        queryset = Property.objects.filter(owner=owner)
        context = {
            'owner': owner,
            'queryset': queryset,
        }
        return render(request, self.template_name, context)


# classes for the payments
# ------------------------------------------------------------------------------------
class PaymentCreate(CreateView):
    model = Payment
    fields = ['amount', 'description']

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            plot = Property.objects.get(pk=self.kwargs['property_pk'])
            received_from = plot.owner

            form.instance.received_from = received_from
            form.instance.property = plot
            form.instance.received_by = self.request.user
            form.instance.payment_number = Payment.generate_payment_number(form.instance)
            plot.balance = (plot.balance - form.instance.amount)
            plot.save()
            return super(PaymentCreate, self).form_valid(form)

        else:
            return redirect('lrms:cover')


class PaymentDetail(DetailView):
    model = Payment
    template_name = 'lrms/payment_detail.html'


class PaymentHistory(TemplateView):
    template_name = 'lrms/payment_history.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            plot = Property.objects.get(pk=self.kwargs['property_pk'])
            payment_history = plot.payment_set.all()
            context = {
                'property': plot,
                'payment_history': payment_history,

            }
            return render(request, self.template_name, context)
        else:
            return redirect('lrms:cover')


# User CreateViews
class SignUp(CreateView):
    form_class = LandsUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class Tafela(View):

    def get(self, request, nangoma=None):
        plot = Property.objects.get(pk=nangoma)
        received_from = plot.owner
        # balance = plot.balance - (form.instance.amount)
        context = {
            'test': nangoma,
            'owner': received_from,
            'plot': plot,
            # 'balance': balance,
        }
        return render(request, 'lrms/test.html', context)


class LandsUserProfile(DetailView):
    model = LandsUser
    context_object_name = 'profile'
    template_name = 'lrms/lands_profile.html'

templates/lrms/cover.html
<!DOCTYPE html>
{% load static %}
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/favicon.ico">

    <title>Welcome To LRMS</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/cover/cover.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">LRMS</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'lrms:home' %}">Home</a>
              <!-- add link to company website contact page -->
            <a class="nav-link" href="tel: +260974020545">Contact Elysian</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Land Records Management System</h1>
        <p class="lead">Land Record Management System (LRMS) is an electronic record system for storege and retrival of all land 
        records kept by Zambian Councils. This allows for transparency in land and lease management.</p>
        <p class="lead">
          <a href="{% url 'lrms:login' %}" class="btn btn-lg btn-secondary">Login</a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Copyright <a href="">Elysian</a>, by <a href="">Front Dev Team</a>.</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'bootstrap/cover/jquery-3.3.1.slim.min.js.download' %}"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">

    </script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'bootstrap/cover/popper.min.js.download' %}"></script>
    <script src="{% static 'bootstrap/cover/bootstrap.min.js.download' %}"></script>
  
  </body>
</html>

templates/lrms/home.html
{% extends 'lrms/base.html' %}
{% block title %}LRMS Home{%endblock%}
{% block content %}

    <h2 align="center">Welcome to LRMS</h2>
     <p class="lead" align="center">
     Enter a house number below to make payments for the house and get access to other information.
     </p>

        <h6 class="text-center">Enter a Hause Number Below.</h6>
    <form class="form-inline justify-content-center mt-2 mt-md-0" action="" method="get">
        <input class="form-control mr-sm-2" type="text" placeholder="Search House Number"
               aria-label="Search" name="q" value="{{ request.GET.q }}">
        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search" />
    </form>
        {% if query_list %}
            <hr style="height: auto">
            <h4>Search Results</h4>
            {% for query in query_list %}
                <a href="{% url 'lrms:property_page' property_pk=query.id %}">{{ query }}</a><br>
            {% endfor %}
        {% else %}
            {% if query_list != None %}
            <h6 class="alert-danger text-center">"{{ request.GET.q }}" Does Not Match Any House Number in the System.</h6>
            {% endif %}
        {% endif %}
{% endblock %}

templates/lrms/lands_profile.html
{% extends 'lrms/base.html' %}
{% block title %}Lands User Profile{% endblock %}

{% block content %}
    <h5>Profile for {{ profile.get_full_name }}.</h5>
    <h6>Username: {{ profile.username }}</h6>
    <a class="btn btn-primary" href="#">Update Profile</a>

{% endblock %}

{% block list_content %}
    <p class="form-text">
        Man Number: {{ profile.man_number }}<hr style="height: auto;">
        Position: {{ profile.position }}<hr style="height: auto;">
        Local Authority: {{ profile.local_authority }}<hr style="height: auto;">
        Phone: {{ profile.phone }}<hr style="height: auto;">
        Email: {{ profile.email }}
    </p>
{% endblock %}

templates/lrms/owner_create.html
{% extends 'lrms/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Owner{% endblock %}

{% block content %}
    <div class="text-center">
    {% if non_existing_owner == '0' %}
            <p class="lead" align="center">Enter an NRC below to check if the owner already exists(Already Owns a Plot)</p>
         <form class="form-inline justify-content-center mt-2 mt-md-0" action="{% url 'lrms:nrc_check' %}" method="get">
             {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" name="nrc" placeholder="Enter Owner NRC">
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Check">
         </form>
            <hr style="height: auto">
            <h5 class="lead font-weight-bold" align="center">Or</h5>
            <hr style="height: auto">
        {% endif %}
        {% if non_existing_owner == '1' %}
            <p class="text-warning">An Owner With The NRC You Entered Does Not Exist Or You Entered The NRC Incorrectly</p>
            <hr style="height: auto">
        {% endif %}

        <p class="lead" align="center">Create a New owner by filling in the form below(First Ever Plot)</p>
        <div class="card">
            <div class="card-header">
            <h5>Owner Create Form</h5>
            </div>
            <div class="card-body">
                <form class="form-inline mt-2 mt-md-0 card" action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Add Owner">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/lrms/owner_detail.html
{% extends 'lrms/base.html' %}
{% block title %}
    Owner Details
{% endblock %}

{% block content %}
    <h3>{{ ownerprofile }}</h3>
    <h6>Gender: {{ ownerprofile.gender }}</h6>
    <h6>NRC: {{ ownerprofile.nrc }}</h6>
    <h6>Age: {{ ownerprofile.age }}</h6>
    <h6>Telephone: {{ ownerprofile.telephone }}</h6>
    <h6>Address: {{ ownerprofile.address }}</h6>
    <h6>Email: {{ ownerprofile.email }}</h6>
    <a class="btn btn-primary" href="{% url 'lrms:property_list_specific' owner_pk=ownerprofile.pk%}">Full Property List</a>

{% endblock %}

templates/lrms/owner_property_list.html
{% extends 'lrms/base.html' %}
{% block title %}Property List{% endblock %}

{% block content %}
    <h4>Property List For {{ owner }}</h4>
    <hr style="height: auto">
    <a class="btn btn-primary" href="{% url 'lrms:owner_detail' pk=owner.pk %}">Back To Owner Details</a>
{% endblock content%}

{% block list_content %}


    <div class="card mb-4">
		<div class="card-block">
			<h3 class="card-title">List Of Properties [Total: {{ queryset.count }}]</h3>
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Holding Number</th>
							<th>Local Authority</th>
							<th>Area</th>
							<th>Type</th>
						</tr>
					</thead>
					<tbody>
                    {% for plot in queryset %}
                        <tr>
                            <td><a href="{% url 'lrms:property_detail' pk=plot.pk%}">{{ plot.holding_number }}</a></td>
							<td>{{ plot.local_authority }}</td>
							<td>{{ plot.area }}</td>
							<td>{{ plot.type }}</td>
						</tr>

                    {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
</div>
{% endblock list_content %}

templates/lrms/payment_detail.html
{% extends 'lrms/base.html' %}

{% block content %}
<h3 class="text-center">PAYMENT FOR: {{ payment.property }}</h3>
    <hr style="height: auto">
    <h4>Received From: {{ payment.received_from }}</h4>
    <h4>Received By: {{ payment.received_by }}</h4>
    <h4>Amount: K{{ payment.amount }}</h4>
    <h4>Description: {{ payment.description }}</h4>
    <h4>Date: {{ payment.date }}</h4>
    <hr style="height: auto">
    <a class="btn btn-primary" href="{% url 'lrms:property_page' property_pk=payment.property.pk %}">Back To Property Details</a>
    <a class="btn btn-primary" href="{% url 'lrms:payment_history' property_pk=payment.property.pk %}">Payment History</a>
{% endblock %}

templates/lrms/payment_form.html
{% extends 'lrms/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center">Fill in the form below to complete the payment.</h3>
<form action="" method="post" class="text-center">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Add Payment" />
</form>
{% endblock %}

templates/lrms/payment_history.html
{% extends 'lrms/base.html' %}
{% block content %}
    <h4>Payment History For {{ property}}</h4>
    <hr style="height: auto">
    <ol>
        {% for payment in payment_history %}
            <li>
                <a class="btn-sm btn-success" href="{% url 'lrms:payment_detail' pk=payment.pk%}">{{ payment }}</a>
            </li>
            <hr style="height: auto">
        {% endfor %}
    </ol>
{% endblock %}

templates/lrms/property_detail.html
{% extends 'lrms/base.html' %}
{% block content %}
    <div class="text-center" >
        <h3>{{ property }}</h3>
    </div>
    <ol class="badge-success">
        <li>Property Owner: {{ property.owner }}</li>
        <li>Property Successor: {{ property.successor}} - {{ property.successor_relation }}</li>
        <li>Property Area: {{ property.area }}</li>
        <li>Holding Number: {{ property.holding_number }}</li>
        <li>Property Type: {{ property.type }}</li>
        <li>Local Authority: {{ property.local_authority }}</li>
        <li>Current Balance: {{ property.balance }}</li>
    </ol>
    <a class="btn btn-primary" href="{% url 'lrms:property_page' property_pk=property.pk %}">Property Page</a>
{% endblock %}

templates/lrms/property_list.html
{% extends 'lrms/base.html' %}
{% block content %}
        <ol>
            {% for property in object_list %}
            <li>
                <a href={{ property.get_absolute_url }}>{{ property }}</a>
            </li>
            {% endfor %}
        </ol>
{% endblock %}

templates/lrms/property_page.html
{% extends 'lrms/base.html' %}
{% block content %}
    <h3 class="text-center">
        {{ property }}
    </h3>
    <hr style="height: auto">
    <div align="center">
        <a class="btn btn-sm btn-primary" href="{% url 'lrms:payment_add' property_pk=property.pk%}"> Make Payment</a>
        <a class="btn btn-sm btn-primary" href="{% url 'lrms:payment_history' property_pk=property.pk%}">Payment History</a>
        <a class="btn btn-sm btn-primary" href="{% url 'lrms:property_detail' pk=property.pk %}">Full Property Details</a>
        <a class="btn btn-sm btn-primary" href="{% url 'lrms:owner_detail' pk=property.owner.pk%}">Owner Details</a>
    </div>
    <hr style="height: auto">

    <div class="container">
        <div class="jumbotron-fluid">
            <h5>{{ property.holding_number.upper}}</h5><br>
            <h5>{{ property.owner }}</h5><br>
            <h5>{{ property.area }}</h5>
        </div>
    </div>

{% endblock %}

templates/lrms/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<h3>{{ test }}</h3>
<h4>{{ plot }}</h4>
<h4>{{ owner }}</h4>
</body>
</html>